version: 2.0
id: test-colophon-repo-9
about:
  title: test-colophon-repo-9
contacts:
  - name: Matt Seburn
    email: matt.seburn@telus.com
environments:
  - title: dummy
    uri: https://github.com/test-colophon-org/test-colophon-repo-9
